using tickets_shop.UI.Features.Menus;
using tickets_shop.UI.Features.Menus.MenuBuilders;

namespace tickets_shop.UI.Features.UIServices.Menu;

/// <summary>
/// A core application service responsible for displaying menus and collecting user input
/// for option selection.
/// </summary>
public class MenuService: UIService
{
    // The list of menu items generated by the current MenuBuilder.
    private IReadOnlyList<MenuItem>? _options;
    
    /// <summary>
    /// Gets or sets the builder responsible for defining the structure and content of the current menu.
    /// </summary>
    public MenuBuilderTemplate? MenuBuilder { get; set; }
    
    protected override string Subtitle => MenuBuilder!.Title;
    
    /// <summary>
    /// Generates the menu options using the assigned MenuBuilder and displays them to the console.
    /// </summary>
    protected override void DisplayCore()
    {
        // 1. Build the menu items
        _options = MenuBuilder!.BuildMenu();
        
        // 2. Display the menu items with newlines in between
        bool first = true;        
        foreach (var menuItem in _options)
        {
            if (!first) ShowMessage("\n");
            ShowMessage(menuItem.ToString());
            first = false;
        }
    }

    /// <summary>
    /// Prompts the user to select a menu option, continuously looping and redisplaying the content
    /// until a valid option ID is entered.
    /// </summary>
    /// <returns>The selected MenuItem object.</returns>
    /// <exception cref="ArgumentNullException">Thrown if the menu options have not been built.</exception>
    public MenuItem ChooseOption()
    {
        if (_options is null) throw new ArgumentNullException(nameof(_options));

        bool invalidOption = false;
        
        while (true)
        {
            // Always display the full menu before prompting for selection
            DisplayContent();
            
            if (invalidOption) ShowMessage("Invalid option. Try again.\n");
            
            var optionId = GetInput("Select: ");
            try
            {
                // Find the option whose ID matches the user's input
                var item = _options.First(o => o.Id == optionId);
                return item;
            }
            catch (InvalidOperationException)
            {
                // If First() fails to find a matching option, InvalidOperationException is thrown
                invalidOption = true;   
            }
        }
    }
}